"""Add payment webhook events

Revision ID: 8d27c895a5fc
Revises: 635c8445ac98
Create Date: 2026-08-25 11:14:43.195936+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d27c895a5fc'
down_revision: Union[str, None] = '635c8445ac98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'RECEIVED'"), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_payment_webhook_events_event_id', 'payment_webhook_events', ['event_id'], unique=False)
    op.create_index('idx_payment_webhook_events_status', 'payment_webhook_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_webhook_events_status', table_name='payment_webhook_events')
    op.drop_index('idx_payment_webhook_events_event_id', table_name='payment_webhook_events')
    op.drop_table('payment_webhook_events')
    # ### end Alembic commands ###
