"""add_inventory_reservation

Revision ID: 28aa134794b6
Revises: 8d27c895a5fc
Create Date: 2026-08-26 05:30:52.192534+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28aa134794b6'
down_revision: Union[str, None] = '8d27c895a5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_reservations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('reserved', 'committed', 'released', 'expired', 'fulfilled')", name='ck_inventory_reservation_status'),
    sa.CheckConstraint('quantity > 0', name='ck_inventory_reservation_quantity_positive'),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_id')
    )
    op.create_index('idx_inventory_reservations_expires_at', 'inventory_reservations', ['expires_at'], unique=False)
    op.create_index('idx_inventory_reservations_status', 'inventory_reservations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inventory_reservations_status', table_name='inventory_reservations')
    op.drop_index('idx_inventory_reservations_expires_at', table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    # ### end Alembic commands ###
