"""create core NEXORA domain models

Revision ID: 635c8445ac98
Revises: 
Create Date: 2026-08-23 06:29:27.440954+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '635c8445ac98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'blocked')", name='ck_buyer_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_buyers_status', 'buyers', ['status'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended')", name='ck_merchant_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_merchants_status', 'merchants', ['status'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('minimum_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('maximum_discount_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('maximum_autonomous_transaction', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('human_approval_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('max_negotiation_rounds', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('max_delivery_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('min_warranty_months', sa.Integer(), server_default=sa.text('12'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_negotiation_rounds > 0', name='ck_policy_max_rounds_positive'),
    sa.CheckConstraint('maximum_autonomous_transaction > 0', name='ck_policy_autonomous_limit_positive'),
    sa.CheckConstraint('maximum_discount_percent >= 0 AND maximum_discount_percent <= 100', name='ck_policy_discount_range'),
    sa.CheckConstraint('minimum_price > 0', name='ck_policy_minimum_price_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_policies_merchant_id', 'policies', ['merchant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('inventory', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'out_of_stock')", name='ck_product_status'),
    sa.CheckConstraint('inventory >= 0', name='ck_product_inventory_non_negative'),
    sa.CheckConstraint('price > 0', name='ck_product_price_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'sku', name='uq_product_merchant_sku')
    )
    op.create_index('idx_products_merchant_id', 'products', ['merchant_id'], unique=False)
    op.create_index('idx_products_status', 'products', ['status'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default=sa.text("'discover'"), nullable=False),
    sa.Column('round_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_rounds', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('discover', 'request', 'offer', 'counter_offer', 'accepted', 'rejected', 'expired')", name='ck_negotiation_state'),
    sa.CheckConstraint('max_rounds > 0', name='ck_negotiation_max_rounds_positive'),
    sa.CheckConstraint('round_count >= 0', name='ck_negotiation_round_count_non_negative'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_negotiations_buyer_id', 'negotiations', ['buyer_id'], unique=False)
    op.create_index('idx_negotiations_merchant_id', 'negotiations', ['merchant_id'], unique=False)
    op.create_index('idx_negotiations_state', 'negotiations', ['state'], unique=False)
    op.create_table('agreements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('negotiation_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('payment_terms', sa.String(length=50), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('discounts_applied', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('policy_decision', sa.String(length=50), nullable=True),
    sa.Column('policy_checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('policy_validated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('blocking_reason', sa.Text(), nullable=True),
    sa.Column('agreement_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending_validation'"), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delivery_days > 0', name='ck_agreement_delivery_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_agreement_quantity_positive'),
    sa.CheckConstraint('total_amount > 0', name='ck_agreement_total_positive'),
    sa.CheckConstraint('unit_price > 0', name='ck_agreement_unit_price_positive'),
    sa.CheckConstraint('warranty_months >= 0', name='ck_agreement_warranty_non_negative'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negotiation_id')
    )
    op.create_index('idx_agreements_buyer_id', 'agreements', ['buyer_id'], unique=False)
    op.create_index('idx_agreements_merchant_id', 'agreements', ['merchant_id'], unique=False)
    op.create_index('idx_agreements_negotiation_id', 'agreements', ['negotiation_id'], unique=False)
    op.create_index('idx_agreements_status', 'agreements', ['status'], unique=False)
    op.create_table('negotiation_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('negotiation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("message_type IN ('request', 'offer', 'counter_offer', 'accept', 'reject', 'system_event')", name='ck_message_type'),
    sa.CheckConstraint("sender_type IN ('buyer_agent', 'merchant_agent', 'system')", name='ck_message_sender_type'),
    sa.CheckConstraint('sequence_number > 0', name='ck_message_sequence_positive'),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negotiation_id', 'sequence_number', name='uq_message_negotiation_sequence')
    )
    op.create_index('idx_messages_negotiation_id', 'negotiation_messages', ['negotiation_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'created'"), nullable=False),
    sa.Column('captured_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created', 'authorized', 'captured', 'failed', 'refunded', 'cancelled')", name='ck_payment_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index('idx_payments_agreement_id', 'payments', ['agreement_id'], unique=False)
    op.create_index('idx_payments_razorpay_order_id', 'payments', ['razorpay_order_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_razorpay_order_id', table_name='payments')
    op.drop_index('idx_payments_agreement_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_messages_negotiation_id', table_name='negotiation_messages')
    op.drop_table('negotiation_messages')
    op.drop_index('idx_agreements_status', table_name='agreements')
    op.drop_index('idx_agreements_negotiation_id', table_name='agreements')
    op.drop_index('idx_agreements_merchant_id', table_name='agreements')
    op.drop_index('idx_agreements_buyer_id', table_name='agreements')
    op.drop_table('agreements')
    op.drop_index('idx_negotiations_state', table_name='negotiations')
    op.drop_index('idx_negotiations_merchant_id', table_name='negotiations')
    op.drop_index('idx_negotiations_buyer_id', table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index('idx_products_status', table_name='products')
    op.drop_index('idx_products_merchant_id', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_policies_merchant_id', table_name='policies')
    op.drop_table('policies')
    op.drop_index('idx_merchants_status', table_name='merchants')
    op.drop_table('merchants')
    op.drop_index('idx_buyers_status', table_name='buyers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
