"""
NEXORA — Buyer Constraint Engine

Deterministic constraint validation for the Buyer Agent.
Ensures that the LLM's proposals or the merchant's counteroffers do not violate
the buyer's strict financial limits, especially maximum budget.
"""
from decimal import Decimal
from typing import NamedTuple

from app.agents.buyer.schemas import BuyerIntent


class ConstraintResult(NamedTuple):
    passed: bool
    reasons: list[str]


class BuyerConstraintEngine:
    """
    Deterministically evaluates financial constraints.
    "LLMs PROPOSE. DETERMINISTIC SYSTEMS DECIDE."
    """
    
    def evaluate_proposal(self, intent: BuyerIntent, unit_price: Decimal, quantity: Decimal) -> ConstraintResult:
        """
        Evaluate a proposal (either generated by the buyer LLM or received from the merchant).
        """
        reasons = []
        
        # 1. Quantity Validation
        if quantity != Decimal(intent.quantity):
            reasons.append(f"Quantity mismatch: expected {intent.quantity}, got {quantity}")
            
        # 2. Total Amount / Budget Validation
        total_amount = (unit_price * quantity).quantize(Decimal("0.01"))
        
        if total_amount > intent.maximum_budget:
            reasons.append(
                f"Budget exceeded: total amount {total_amount} exceeds maximum budget {intent.maximum_budget}"
            )
            
        return ConstraintResult(
            passed=len(reasons) == 0,
            reasons=reasons
        )
